discourse-choujiang:
  choujiang_enabled:
    default: true
    client: true
  choujiang_tag:
    default: "抽奖活动"
    client: true
  choujiang_drawn_tag:
    default: "抽奖结束"
    client: true
